import { ENV } from "./env";

export const ASSETS = {
  ALL_MENU: "/images/all-menu.svg",
  BANK_BCA_ICON: "/images/footer/bca.svg",
  BANK_BNI_ICON: "/images/footer/bni.svg",
  BANK_MANDIRI_ICON: "/images/footer/mandiri.svg",
  BANK_PERMATA_ICON: "/images/footer/permata.svg",
  BANNER_ADS: "/images/banner-ads.webp",
  BANNER_CARDIAC_CLINIC_INFO: "/images/banner-cardiac-clinic-info.png",
  BANNER_CARDIAC_CLINIC_INFO_MOBILE:
    "/images/banner-cardiac-clinic-info-mobile.png",
  BANNER_CARDIAC_CLINIC_TELEMEDICINE:
    "/images/banner-cardiac-clinic-telemedicine.png",
  BANNER_CARDIAC_CLINIC_TELEMEDICINE_MOBILE:
    "/images/banner-cardiac-clinic-telemedicine-mobile.png",
  BANNER_CARDIAC_HEALTH_TOOL: "/images/banner-cardiac-health-tool.png",
  BANNER_CARDIAC_HEALTH_TOOL_MOBILE:
    "/images/banner-cardiac-health-tool-mobile.png",
  BANNER_CLINIC_BOOKING_MOBILE: "/images/banner-clinic-booking-mobile.png",
  BANNER_INTERNIST_CLINIC_BOOKING:
    "/images/banner-internist-clinic-booking.png",
  BANNER_INTERNIST_CLINIC_BOOKING_MOBILE:
    "/images/banner-internist-clinic-booking-mobile.png",
  BANNER_INTERNIST_CLINIC_TELEMEDICINE:
    "/images/banner-internist-clinic-telemedicine.png",
  BANNER_INTERNIST_CLINIC_TELEMEDICINE_MOBILE:
    "/images/banner-internist-clinic-telemedicine-mobile.png",
  BG_CT_SCAN: "/images/bg-ct-scan.svg",
  BG_DOT_LEFT: "/images/background-dot-left.svg",
  BG_DOT_RIGHT: "/images/background-dot-right.svg",
  BG_JADWAL_CHAT: "/images/bg-jadwal-chat.svg",
  BG_LUNGS: "/images/bg-lungs.svg",
  BG_PHOTO: "/images/bg-photo.svg",
  BG_RONTGEN: "/images/bg-rontgen.svg",
  BG_TES_DARAH: "/images/bg-test-darah.svg",
  BG_TES_KESEHATAN: "/images/bg-tes-kesehatan.webp",
  BG_TES_KESEHATAN_MENTAL: "/images/bg-tes-kesehatan-mental.png",
  BG_USG: "/images/bg-usg.svg",
  BPJS_LOGO: "/images/bpjs-logo.svg",
  CAMPAIGN_BANNER: "/images/campaign-banner.jpg",
  CANCEL_PRESCRIPTION: "/images/cancel-prescription.svg",
  CARDIAC_NAVIGATION_LOGO: "/images/cardiac-nav-logo.svg",
  CC_AMERICAN_EXPRESS_ICON: "/images/footer/americanexpress.svg",
  CC_JCB_ICON: "/images/footer/jcb.svg",
  CC_MASTER_CARD_ICON: "/images/footer/mastercard.svg",
  CC_VISA_ICON: "/images/footer/visa.svg",
  CHAT_ENDED: "/images/chat-ended.svg",
  CONSULTATION_ICON: "/images/consultation-icon.svg",
  CONSULTATION_OFF: "/images/consultation-off.svg",
  CONSULTATION_ON: "/images/consultation-on.svg",
  CONSULTATION_THANK_YOU: "/images/consultation-thank-you.svg",
  CONTACT_PHONE_ICON: "/images/footer/contact_phone.svg",
  CORP_MEMBER: "/images/corp-member.svg",
  CREDIT_CARD_SPRITE: "/images/footer/cc.png",
  DELAY_PAYMENT: `${ENV.PAYMENTQ_STATIC_URL}/images/delay-payment.png`,
  DELETE_FORUM_COMMENT: "/images/delete-forum-comment.webp",
  DOCTOR_END_CHAT: "/images/doctor-end-chat.svg",
  DOCTOR_NOTE_BLUE: "/images/doctor-note-blue.svg",
  DOCTOR_NOTE_DESKTOP: "/images/doctor-note-desktop.svg",
  DOCTOR_NOTE_MWEB: "/images/doctor-note-mweb.svg",
  DOWNLOAD_APPLE_ICON: "/images/footer/appstore.svg",
  DOWNLOAD_GOOGLE_ICON: "/images/footer/playstore.svg",
  EMPTY: "/images/empty.svg",
  EMPTY_BOOKING_DOCTOR: "/images/empty-booking-doctor.svg",
  EMPTY_CART: "/images/empty-cart.svg",
  EMPTY_FILTERS: "/images/empty-filter.svg",
  EMPTY_HCP_LIST: "/images/empty-hcp-list.svg",
  EMPTY_HEALTH_SERVICE_APPOINTMENT:
    "/images/empty-health-service-appointment.svg",
  EMPTY_MENTAL_HEALTH_RECORD: "/images/empty-mental-health-record.svg",
  EMPTY_MY_PRESCRIPTIONS: "/images/illustration-no-receipt.svg",
  EMPTY_TELEMED_HISTORY_LIST: "/images/empty-telemed-history.svg",
  ERROR_ICON: "/images/error-icon.svg",
  EXPLORE_OFF: "/images/explore-off.svg",
  EXPLORE_ON: "/images/explore-on.svg",
  // F
  FEEDBACK_ICON: "/images/feedback-icon.svg",
  FORUM_BANNER: "/images/forum-banner.svg",
  FORUM_FORM_BANNER: "/images/forum-form-banner.png",
  FORUM_TELEMED_BANNER: "/images/forum-telemed-banner.webp",
  // G
  GENERIC_WARNING: "/images/generic-warning.svg",
  GOPAY_ICON: "/images/footer/gopay.svg",
  HCF_PARTNER_MWEB_BG: "/images/hcf-partner-mweb-bg.jpg",
  HCF_PARTNER_WEB_BG: "/images/hcf-partner-web-bg.svg",
  HEALTH_TOOL_HEADLINE: "/images/health-tool-headline.svg",
  ICON_AFTERNOON: "/images/icon-afternoon.svg",
  ICON_BOTTLE: "/images/icon-bottle.svg",
  ICON_COMMENT_LIKE: "/images/icon-comment-like.png",
  ICON_CUT: "/images/icon-cut.svg",
  ICON_DRINKING_BOTTLES: "/images/icon-drinking-bottles.png",
  ICON_FREE_SHIPPING: "/images/icon-free-shipping.svg",
  ICON_GLUKOMETER: "/images/icon-glukometer.png",
  ICON_GLUKOMETER_SHADOW: "/images/icon-glukometer-shadow.png",
  ICON_HOT_STOMACH: "/images/icon-hot-stomach.png",
  ICON_INJECT: "/images/icon-inject.svg",
  ICON_MORNING: "/images/icon-morning.svg",
  ICON_NIGHT: "/images/icon-night.svg",
  ICON_NOON: "/images/icon-noon.svg",
  ICON_STOMACH: "/images/icon-stomach.png",
  ICON_VOUCHER: "/images/icon-voucher.svg",
  ILLUSTRATION_BABY: "/images/illustration-baby.png",
  ILLUSTRATION_BANNER_BOOKING: "/images/illustration-banner-booking.png",
  ILLUSTRATION_BANNER_BOOKING_MOBILE:
    "/images/illustration-banner-booking-mobile.png",
  ILLUSTRATION_BANNER_PRODUCT: "/images/illustration-banner-product.png",
  ILLUSTRATION_BANNER_PRODUCT_INTERNIST:
    "/images/illustration-banner-product-internist.png",
  ILLUSTRATION_BANNER_PRODUCT_INTERNIST_MOBILE:
    "/images/illustration-banner-product-internist-mobile.png",
  ILLUSTRATION_BANNER_PRODUCT_MOBILE:
    "/images/illustration-banner-product-mobile.png",
  ILLUSTRATION_BANNER_TELEMEDICINE:
    "/images/illustration-banner-telemedicine.png",
  ILLUSTRATION_BANNER_TELEMEDICINE_MOBILE:
    "/images/illustration-banner-telemedicine-mobile.png",
  ILLUSTRATION_BATITA: "/images/illustration-batita.png",
  ILLUSTRATION_BOTTLE_DIABETES: "/images/illustration-bottle-diabetes.png",
  ILLUSTRATION_BRONKITIS: "/images/illustration-bronkitis.png",
  ILLUSTRATION_CARDIAC: "/images/illustration-cardiac.png",
  ILLUSTRATION_CARDIAC_HEALTH_TOOL:
    "/images/illustration-cardiac-health-tool.png",
  ILLUSTRATION_CARDIAC_MOBILE: "/images/illustration-cardiac-mobile.png",
  ILLUSTRATION_CHAT_ENDED: "/images/illustration-chat-ended.svg",
  ILLUSTRATION_CHILD: "/images/illustration-child.png",
  ILLUSTRATION_CHILD_HEADLINES: "/images/child-headlines.png",
  ILLUSTRATION_CHILD_HEADLINES_MOBILE: "/images/child-headlines-mobile.png",
  ILLUSTRATION_DIABETES: "/images/illustration-diabetes.png",
  ILLUSTRATION_DOCTOR_BUSY: "/images/illustration-doctor-busy.svg",
  ILLUSTRATION_DOCTOR_DIABETES: "/images/illustration-doctor-diabetes.png",
  ILLUSTRATION_END_CHAT_CONFIRMATION:
    "/images/illustration-end-chat-confirmation.svg",
  ILLUSTRATION_FAILED: "/images/illustration-failed.svg",
  ILLUSTRATION_FAST_FACT: "/images/illustration-fast-fact.png",
  ILLUSTRATION_FAST_FACT_MOBILE: "/images/illustration-fast-fact-mobile.png",
  ILLUSTRATION_FORUM: "/images/illustration-forum.png",
  ILLUSTRATION_FORUM_MOBILE: "/images/illustration-forum-mobile.png",
  ILLUSTRATION_GERD: "/images/illustration-gerd.png",
  ILLUSTRATION_HIPERTENSI: "/images/illustration-hipertensi.png",
  ILLUSTRATION_INTERNIST: "/images/illustration-internist.png",
  ILLUSTRATION_INTERNIST_MOBILE: "/images/illustration-internist-mobile.png",
  ILLUSTRATION_KURIR: "/images/illustration-kurir.svg",
  ILLUSTRATION_LOGIN: "/images/illustration-login.svg",
  ILLUSTRATION_PARK: "/images/illustration-park.svg",
  ILLUSTRATION_STETOSKOP: "/images/illustration-stetoskop.png",
  ILLUSTRATION_TELEMED_DOC_REST: "/images/illustration-telemed-doc-rest.svg",
  ILLUSTRATION_TIMES_OUT: "/images/time-out.svg",
  ILLUSTRATION_TIMES_UP: "/images/illustration-times-up.svg",
  ILLUSTRATION_TODDLER: "/images/illustration-toddler.png",
  ILLUSTRATION_WAITING: "/images/illustration-waiting.svg",
  INFO_ICON: `${ENV.PAYMENTQ_STATIC_URL}/images/info.svg`,
  INTERNIST_NAVIGATION_LOGO: "/images/internist-nav-logo.svg",
  KONSUL_01_CHAT_5000: "/images/konsul-01-chat-5000.svg",
  KONSUL_01_CHAT_GRATIS: "/images/konsul-01-chat-gratis.svg",
  KONSUL_02_DOKTER_PENGALAMAN: "/images/konsul-02-dokter-pengalaman.svg",
  KONSUL_03_CUKUP_DENGAN_CHAT: "/images/konsul-03-cukup-dengan-chat.svg",
  KONSUL_04_CARI_DOKTER_LAIN: "/images/konsul-04-cari-dokter-lain.svg",
  MENU_ICON_ACTIVITY: "/images/menu-icon-activity.svg",
  MENU_ICON_CORPORATE: "/images/menu-icon-corporate.svg",
  MENU_ICON_ECLAIM: "/images/menu-icon-eklaim.svg",
  MENU_ICON_FAMILY: "/images/menu-icon-family.svg",
  MENU_ICON_RECORD: "/images/menu-icon-record.svg",
  MENU_ICON_TRANSACTION: "/images/menu-icon-transaction.svg",
  MERCHANT_REVIEW_EMPTY: "/images/merchant-review-empty.svg",
  MINISTRY_OF_HEALTH: "/images/logo-ministry-of-health.svg",
  MODAL_CANCEL_PAYMENT: `${ENV.PAYMENTQ_STATIC_URL}/images/cancel-payment.svg`,
  NAVIGATION_BG: "/images/navigation-bg.svg",
  NO_IMAGE: "https://www.sehatq.com/public/assets/img/no-image.jpg",
  NO_IMAGE_DOCTOR_FEMALE: "/images/no-image-doctor-female.png",
  NO_IMAGE_DOCTOR_MALE: "/images/no-image-doctor-male.png",
  OTHER_MENU: "/images/other-menu.svg",
  PEDIATRIC_NAVIGATION_LOGO: "/images/pediatric-nav-logo.svg",
  PRESCRIPTION: "/images/prescription.svg",
  PRESCRIPTION_EXAMPLE: "/images/prescription-example.svg",
  PRESCRIPTION_RECOMMENDATION: "/images/prescription-recommendation.svg",
  PROFILE_PLACEHOLDER_MAN: "/images/profile_placeholder_man.svg",
  PROFILE_PLACEHOLDER_WOMAN: "/images/profile_placeholder_woman.svg",
  PROFILE_VERIFIED: "/images/profile-verified.svg",
  PROMO_OFF: "/images/promo-off.svg",
  PROMO_ON: "/images/promo-on.svg",
  QUOTE_ICON_CLOSE: "/images/close_quote.svg",
  QUOTE_ICON_OPEN: "/images/open_quote.svg",
  RECOMENDED_ICON: `${ENV.PAYMENTQ_STATIC_URL}/images/recomended.svg`,
  REGULAR_TELEMED_BANNER: "/images/regular-telemed-photo.jpeg",
  REGULAR_TELEMED_VOUCHER: "/images/regular-telemed-voucher.png",
  REGULAR_TELEMED_VOUCHER_MOBILE: "/images/regular-telemed-voucher-mobile.svg",
  REVIEW_CS_SUCCESS: "/images/review-cs-success.svg",
  SECURE_ICON: `${ENV.PAYMENTQ_STATIC_URL}/images/secure.svg`,
  SEHATQ: "/images/sehatq-logo.svg",
  SEHATQ_SM: "/images/logo-sehat-sm.svg",
  SEHATQ_WITH_TEXT: "/images/logo-sehatq-with-text.svg",
  SOCIAL_FACEBOOK: "/images/footer/social_fb.svg",
  SOCIAL_FACEBOOK_MIN: "/images/footer/social_fb_grey.svg",
  SOCIAL_IG: "/images/footer/social_ig.svg",
  SOCIAL_IG_MIN: "/images/footer/social_ig_grey.svg",
  SOCIAL_LINKEDIN: "/images/footer/social_linkedin.svg",
  SOCIAL_LINKEDIN_MIN: "/images/footer/social_linkedin_grey.svg",
  SOCIAL_TWITTER: "/images/footer/social_twitter.svg",
  SOCIAL_TWITTER_MIN: "/images/footer/social_twitter_grey.svg",
  SOCIAL_YOUTUBE: "/images/footer/social_youtube.svg",
  SOCIAL_YOUTUBE_MIN: "/images/footer/social_youtube_grey.svg",
  SPECIALITY_OFF: "/images/speciality-off.svg",
  SPECIALITY_ON: "/images/speciality-on.svg",
  SPESIALIST_ICON: "/images/specialist-icon.svg",
  SUCCESS_SUBMIT_FORUM: "/images/success-submit-forum.svg",
  TELEMED_BANNER: "/images/telemed-banner.webp",
  TELEMED_BANNER_CORPORATE_REGISTRATION:
    "/images/banner-telemed-corporate-registration.jpg",
  TELEMED_CORPORATE_MCU: "/images/telemed-corporate-mcu.jpg",
  TELEMED_DOCTORS_BANNER: "/images/doctor-telemed-landing-banner.png",
  TELEMED_LANDING_BG: "/images/bg-telemed-landing.svg",
  TELEMED_LANDING_HCPS_BG: "/images/bg-telemed-landing-hcps.svg",
  TELEMED_LANDING_HCPS_BG2: "/images/bg-telemed-landing-hcps-2.svg",
  TELEMEDICINE: "/images/telemedicine.svg",
  THUMBS_UP: "/images/thumbs-up.svg",
  UNAVAILABLE_AT_THE_MOMENT: "/images/unavailable-at-the-moment.svg",
  WAITING_PAYMENT: `${ENV.PAYMENTQ_STATIC_URL}/images/waiting-for-payment.svg`,
} as const;
