import { ENV } from "./env";

export const URLS = {
  ABOUT_US: "/tentang-kami",
  ARTICLE: "/artikel/[[...slugs]]",
  ARTICLES: "/artikel",
  AUTHOR: "/author/[slug]",
  BOOKING_ONLINE: "/booking",
  CAREERS: "/karir",
  COLLECTIONS: "/kumpulan/[slug]",
  COMPANY_PARTNER: "/mitra-perusahaan",
  CONTACT: "/kontak",
  DISEASE: "/penyakit/[[...slugs]]",
  DISEASES: "/penyakit",
  DRUGS: "/obat",
  EDIT_PROFILE: "/profil/[userId]/detail/edit",
  EDITORIAL: "/kebijakan-editorial",
  EXTERNAL_CART: `${ENV.TOKOQ_DOMAIN}/cart`,
  EXTERNAL_CATEGORIES: `${ENV.TOKOQ_DOMAIN}/kategori`,
  EXTERNAL_CATEGORY: `${ENV.TOKOQ_DOMAIN}/kategori/[slugUrl]`,
  EXTERNAL_HELP: `${ENV.TOKOQ_DOMAIN}/help`,
  EXTERNAL_HOMEPAGE: `${ENV.TOKOQ_DOMAIN}`,
  EXTERNAL_LOGIN: `${ENV.ACCOUNT_DOMAIN}/login`,
  EXTERNAL_LOGIN_EMAIL: `${ENV.ACCOUNT_DOMAIN}/login/email`,
  EXTERNAL_LOGIN_FACEBOOK: `${ENV.ACCOUNT_DOMAIN}/auth/login/facebook`,
  EXTERNAL_LOGIN_GMAIL: `${ENV.ACCOUNT_DOMAIN}/auth/login/google`,
  EXTERNAL_MERCHANT: `${ENV.TOKOQ_DOMAIN}/merchant`,
  EXTERNAL_MERCHANT_REGISTER: `https://docs.google.com/forms/d/e/1FAIpQLSfxZHibIJlzOibd94dkB5mQp2JHPOfFjmADFxCm3OJ4j70_rw/viewform`,
  EXTERNAL_MY_VOUCHER: `${ENV.TOKOQ_DOMAIN}/voucher-saya`,
  EXTERNAL_PRESCRIPTION_CART: `${ENV.TOKOQ_DOMAIN}/cart/prescription/[prescriptionNo]`,
  EXTERNAL_PRESCRIPTION_HISTORY: `${ENV.TOKOQ_DOMAIN}/prescription/history/[prescriptionId]`,
  EXTERNAL_PRESCRIPTION_REQUEST: `${ENV.TOKOQ_DOMAIN}/prescription/upload`,
  EXTERNAL_PRODUCT: `${ENV.TOKOQ_DOMAIN}/produk/[slug]`,
  EXTERNAL_PRODUCTS: `${ENV.TOKOQ_DOMAIN}/produk`,
  EXTERNAL_PROFILE_ORDER: `${ENV.TOKOQ_DOMAIN}/order`,
  EXTERNAL_PROFILE_ORDER_DETAIL: `${ENV.TOKOQ_DOMAIN}/order/[coNumber]/[moSequence]`,
  EXTERNAL_REGISTER: `${ENV.ACCOUNT_DOMAIN}/daftar/email`,
  EXTERNAL_REVIEW_HEALTH_SERVICE: "https://forms.gle/go9oo7HhVGDxqZ9p9",
  EXTERNAL_SEHATQ_FACEBOOK: "https://www.facebook.com/SehatQIndonesia/",
  EXTERNAL_SEHATQ_INSTAGRAM: "https://www.instagram.com/sehatq_id",
  EXTERNAL_SEHATQ_LINKEDIN: "https://www.linkedin.com/company/sehatq",
  EXTERNAL_SEHATQ_TWITTER: "https://twitter.com/sehatq",
  EXTERNAL_SEHATQ_YOUTUBE:
    "https://www.youtube.com/channel/UCOK2bObQGpy2RUMSQejSj5g",
  FORUM: "/forum/[[...slugs]]",
  FORUM_DETAIL: "/forum/_detail/[forumSlug]",
  FORUM_DETAIL_MOBILE: "/forum/_detail/[forumSlug]/_mobile",
  FORUMS: "/forum",
  HEALTH_CARE_FACILITIES: "/faskes/[[...slugs]]",
  HEALTH_CARE_FACILITY: "/faskes/[hcfSlug]",
  HEALTH_CARE_PROFESIONAL: "/dokter/[[...slugs]]",
  HEALTH_CARE_PROFESIONALS: "/dokter/[[...slugs]]",
  HEALTH_SERVICE: "/faskes/[hcfSlug]/layanan-pemeriksaan",
  HEALTH_SERVICE_DETAIL: "/layanan-pemeriksaan/[[...slugs]]",
  HEALTH_SERVICES: "/layanan-pemeriksaan",
  HEALTH_SERVICES_APPOINTMENT: "/layanan-kesehatan",
  HEALTH_TOOL_DETAIL: "/tes-kesehatan/[slug]",
  HEALTH_TOOLS: "/tes-kesehatan",
  HEALTH_TOOLS_MENTAL_FORM: "/tes-kesehatan/tes-kesehatan-mental/mulai",
  HOME: "/",
  INBOX: "/inbox",
  MEDICAL_PROCEDURE: "/tindakan-medis/[slug]",
  MEDICAL_PROCEDURES: "/tindakan-medis",
  MENTAL_HEALTH_TEST: "/tes-kesehatan/tes-kesehatan-mental",
  MERCHANT_DETAIL: "/merchant/[slug]",
  MY_BOOKING_DOCTOR: "/profil/[userId]/aktivitas/booking/[bookingId]",
  MY_BOOKING_DOCTORS: "/profil/[userId]/aktivitas/booking",
  MY_DOCTOR_APPOINTMENTS: "/profil/[userId]/aktivitas/booking",
  MY_HEALTH_SERVICE:
    "/profil/[userId]/aktivitas/layanan-pemeriksaan/[bookingId]",
  MY_HEALTH_SERVICES: "/profil/[userId]/aktivitas/layanan-pemeriksaan",
  MY_MENTAL_RECORD:
    "/profil/[userId]/health-record/tes-kesehatan-mental/[mentalId]",
  MY_MENTAL_RECORDS: "/profil/[userId]/health-record/tes-kesehatan-mental",
  MY_PRESCRIPTIONS: "/profil/[userId]/aktivitas/resep",
  MY_TELEMEDICINES: "/profil/[userId]/aktivitas/telemed",
  PARTNER_CORPORATE: "/mitra-perusahaan",
  PARTNER_HCF: "/mitra-faskes",
  PRESCRIPTION: "/profil/resep/[prescriptionNo]",
  PRESCRIPTION_FORM: "/buat-resep",
  PRESCRIPTION_FORM_THANK_YOU: "/buat-resep/terima-kasih",
  PRIVACY: "/kebijakan-privasi",
  PROFILE: "/profil",
  PROFILE_CORPORATE: "/profil/corporate",
  PROFILE_DETAIL: "/profil/[userId]/detail",
  PROFILE_ECLAIM: "/profil/[userId]/eclaim",
  PROFILE_FAMILY_ADD: "/profil/[userId]/keluarga/tambah",
  PROFILE_FAMILY_DETAIL: "/profil/[memberId]/keluarga/detail",
  PROFILE_FAMILY_LIST: "/profil/[userId]/keluarga",
  PROFILE_HEALTH_TOOL_SCORE_LIST:
    "/profil/[userId]/health-record/[healthToolSlug]",
  PROFILE_HEALTHRECORD_DETAIL_SCORE:
    "/profil/[userId]/health-record/[slug]/[scoreId]",
  PROFILE_HEALTHRECORD_LIST: "/profil/[userId]/health-record",
  PROFILE_MORE: "/profil/more",
  PROFILE_PRESCRIPTIONS: "/profil/resep",
  PROFILE_SETTINGS: "/profil/more/setting",
  PROMOS: "/promo",
  REVIEW: "/review/[slug]",
  REVIEWER: "/reviewer/[slug]",
  REVIEWS: "/review",
  SEARCH: "/cari",
  TAG: "/tag/[slug]",
  TAGS: "/tag",
  TELEMED_CAMPAIGN: "/telemed/campaign/[slug]",
  TELEMED_CAMPAIGNS: "/telemed/campaign",
  TELEMED_CHAT: "/telemed/chat/[consultationId]",
  TELEMED_CHATS: "/telemed/chat",
  TELEMED_DOCTOR: "/telemed/dokter/[slug]",
  TELEMED_FASKES: "/telemed/faskes",
  TELEMED_FASKES_DETAIL: "/telemed/faskes/[hospitalSlug]/[[...slugs]]",
  TELEMED_GENERAL_CHAT_FORM: "/telemed/chat/0",
  TELEMED_HCP_PROFILE: "/telemed/dokter/[slug]",
  TELEMED_HCP_SCHEDULE: "/telemed/dokter/[id]/jadwal",
  TELEMED_HCP_SCHEDULES: "/telemed/dokter/[slug]/jadwal",
  TELEMED_HCPS: "/telemed/spesialis/[[...slugs]]",
  TELEMED_HISTORIES: "/telemed/history",
  TELEMED_HISTORY: "/telemed/history/[consultationId]",
  TELEMED_PAID_CHATS: "/telemed/paid",
  TELEMED_SCHEDULE: "/telemed/jadwal",
  TELEMEDICINE_FORM: "/telemed/form/[consultationId]",
  TELEMEDICINES: "/telemed",
  TNC: "/syarat",
} as const;
